// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrmicmyrhpwmmahynkkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybWljbXlyaHB3bW1haHlua2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjQ2NTYsImV4cCI6MjA2NTk0MDY1Nn0.4wZJ856ejI_OYCf8u83nXdaOPSA49Ljt-Nd1aFOvfj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);